extends: stylelint-config-recommended-vue
rules:
  # https://scottspence.com/posts/stylelint-configuration-for-tailwindcss
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
        - apply
        - variants
        - responsive
        - screen
